version: "3.3"

services:
  db:
    build: ./mysql/
    restart: always
    env_file:
      - ./config/db.env
    ports:
      - "3306:3306"
    networks:
      - dockercompose
    volumes:
      - ./mysql/schema.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    depends_on:
      db:
        condition: service_healthy
    build: ./flask/
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - "/home/renato/development/docker-course/5_compose/6_build_mount_compose/flask:/app"
    networks:
      - dockercompose

networks:
  dockercompose:
